USE master
GO
IF NOT EXISTS (
   SELECT name
   FROM sys.databases
   WHERE name = N'INTREPRINDERE'
)
CREATE DATABASE [INTREPRINDERE]
GO



CREATE TABLE INTREPRINDERE.dbo.INGINERI(
	IdAngajat INT UNIQUE FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	Specialitatea VARCHAR(255),
)


CREATE TABLE INTREPRINDERE.dbo.SECTII(
	IdSectie INT PRIMARY KEY IDENTITY(1,1), 
	Nume VARCHAR(255),
	Buget FLOAT,
)


CREATE TABLE INTREPRINDERE.dbo.ANGAJATI(
	IdAngajat INT PRIMARY KEY IDENTITY(1,1),
	Nume VARCHAR(255) NOT NULL,
	Prenume VARCHAR(255) NOT NULL,
	Data_Nasetii DATE,
	Adresa TEXT,
	Functie TEXT,
	Salariu FLOAT,
	--IdSectie INT NOT NULL REFERENCES SECTII(IdSectie),
	IdSectie INT FOREIGN KEY REFERENCES SECTII(IdSectie)
)


CREATE TABLE INTREPRINDERE.dbo.SECRETARE(
	IdAngajat INT UNIQUE FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	VitezaRedactar FLOAT
)



CREATE TABLE INTREPRINDERE.dbo.DEPENDENTI(
	IdAngajat INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	Nume VARCHAR(255),
	Prenume VARCHAR(255),
	DataNasterii DATE,
	GradRudenie INT
)


CREATE TABLE INTREPRINDERE.dbo.FURNIZOR(
	IdFurnizor INT PRIMARY KEY IDENTITY(1,1),
	Nume VARCHAR(255),
	Prenume VARCHAR(255),
	Adresa VARCHAR(255)
)

CREATE TABLE INTREPRINDERE.dbo.COMPONENTE(
	IdComponenta INT PRIMARY KEY IDENTITY(1,1),
	Denumire VARCHAR(255),
	Descriere VARCHAR(255),
)

CREATE TABLE INTREPRINDERE.dbo.PRODUSE(
	IdProdus INT PRIMARY KEY IDENTITY(1,1),
	Denumire VARCHAR(255),
	Descriere VARCHAR(255),
)

CREATE TABLE INTREPRINDERE.dbo.CLIENTI(
	IdClient INT PRIMARY KEY IDENTITY(1,1),
	Nume VARCHAR(255),
	Prenume VARCHAR(255),
	Adresa VARCHAR(255)
)

CREATE TABLE INTREPRINDERE.dbo.PROIECTE(
	IdProiect INT PRIMARY KEY IDENTITY(1,1),
	Denumire VARCHAR(255),
	Termen DATE,
	Buget FLOAT
)


CREATE TABLE INTREPRINDERE.dbo.ACHIZITII(
	IdAchizitie INT PRIMARY KEY IDENTITY(1,1),
	IdFurnizor INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.FURNIZOR(IdFurnizor),
	IdComponenta INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.COMPONENTE(IdComponenta),
	IdAchizitor INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	Dataa DATE,
	NrComponente INT,
	PretUnitar INT
)


CREATE TABLE INTREPRINDERE.dbo.COMPOZITIE(
	IdComponenta INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.COMPONENTE(IdComponenta),
	IdProdus INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.PRODUSE(IdProdus),
	NrComponente INT
)

CREATE TABLE INTREPRINDERE.dbo.VANZARI(
	IdVanzare INT PRIMARY KEY IDENTITY(1,1),
	IdProdus INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.PRODUSE(IdProdus),
	IdClient INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.CLIENTI(IdClient),
	IdVanzator INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	Dataa DATE,
	NrProduse INT
)

CREATE TABLE INTREPRINDERE.dbo.ACTIVITATI(
	IdProiect INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.PROIECTE(IdProiect),
	IdAngajat INT FOREIGN KEY REFERENCES INTREPRINDERE.dbo.ANGAJATI(IdAngajat),
	Ore INT
)
