
--3.1
SELECT Nume,Prenume,Adresa
FROM INTREPRINDERE.dbo.CLIENTI
WHERE Adresa='Bucuresti'
UNION
SELECT Nume,Prenume,Adresa
FROM INTREPRINDERE.dbo.FURNIZOR
WHERE Adresa = 'Bucuresti'

--3.2
SELECT *
FROM INTREPRINDERE.dbo.ANGAJATI
CROSS JOIN INTREPRINDERE.dbo.SECTII

--3.3
SELECT Nume,Prenume,NrComponente
FROM INTREPRINDERE.dbo.FURNIZOR
INNER JOIN INTREPRINDERE.dbo.ACHIZITII
ON ACHIZITII.IdFurnizor = FURNIZOR.IdFurnizor
WHERE ACHIZITII.NrComponente > 200 OR ACHIZITII.NrComponente = 200;

--3.4
SELECT Nume,Prenume,Denumire
FROM INTREPRINDERE.dbo.ACHIZITII
INNER JOIN INTREPRINDERE.dbo.ANGAJATI
ON ACHIZITII.IdAchizitie = ANGAJATI.IdAngajat
INNER JOIN INTREPRINDERE.dbo.COMPONENTE
ON ACHIZITII.IdComponenta = COMPONENTE.IdComponenta
WHERE COMPONENTE.Denumire = 'Condensator';


--3.5
SELECT Nume,Prenume,Adresa
FROM INTREPRINDERE.dbo.ACHIZITII
INNER JOIN INTREPRINDERE.dbo.FURNIZOR
ON ACHIZITII.IdFurnizor = FURNIZOR.IdFurnizor
INNER JOIN INTREPRINDERE.dbo.COMPONENTE
ON ACHIZITII.IdComponenta = COMPONENTE.IdComponenta
WHERE COMPONENTE.Denumire = 'Rezistenta';

--3.6
SELECT Nume,Prenume,Adresa
FROM INTREPRINDERE.dbo.FURNIZOR
INNER JOIN INTREPRINDERE.dbo.ACHIZITII
ON ACHIZITII.IdFurnizor = FURNIZOR.IdFurnizor
INNER JOIN INTREPRINDERE.dbo.COMPONENTE
ON ACHIZITII.IdComponenta = COMPONENTE.IdComponenta
WHERE COMPONENTE.Denumire = 'Condensator' AND (ACHIZITII.NrComponente > 150 OR ACHIZITII.NrComponente = 150);


--3.7
SELECT Nume,Prenume,Adresa
FROM INTREPRINDERE.dbo.VANZARI
INNER JOIN INTREPRINDERE.dbo.PRODUSE
ON VANZARI.IdProdus = PRODUSE.IdProdus
INNER JOIN INTREPRINDERE.dbo.CLIENTI
ON VANZARI.IdClient = CLIENTI.IdClient
WHERE PRODUSE.Denumire = 'Monitor' AND (VANZARI.NrProduse > 10 OR VANZARI.NrProduse = 10)


--3.8
SELECT Nume,Prenume
FROM INTREPRINDERE.dbo.VANZARI
INNER JOIN INTREPRINDERE.dbo.PRODUSE
ON VANZARI.IdProdus = PRODUSE.IdProdus
INNER JOIN INTREPRINDERE.dbo.ANGAJATI
ON VANZARI.IdVanzator = ANGAJATI.IdAngajat
WHERE PRODUSE.Denumire = 'Monitor';


--3.9
SELECT ANGAJATI.Nume,ANGAJATI.Prenume,ANGAJATI.Data_Nasetii
FROM INTREPRINDERE.dbo.ACTIVITATI
INNER JOIN INTREPRINDERE.dbo.ANGAJATI
ON ACTIVITATI.IdAngajat = ANGAJATI.IdAngajat
INNER JOIN INTREPRINDERE.dbo.PROIECTE
ON PROIECTE.IdProiect = ACTIVITATI.IdProiect
WHERE PROIECTE.Denumire = 'Sistem de achizitii de date'

--3.10

SELECT SECTII.Nume
FROM INTREPRINDERE.dbo.ACTIVITATI
INNER JOIN INTREPRINDERE.dbo.ANGAJATI
ON ACTIVITATI.IdAngajat = ANGAJATI.IdAngajat
INNER JOIN INTREPRINDERE.dbo.SECTII
ON SECTII.IdSectie = ANGAJATI.IdSectie
INNER JOIN INTREPRINDERE.dbo.PROIECTE
ON PROIECTE.IdProiect = ACTIVITATI.IdProiect
WHERE PROIECTE.Denumire = 'Sistem de achizitii de date'

--3.11
SELECT ANGAJATI.Nume, ANGAJATI.Prenume,ANGAJATI.Data_Nasetii
FROM INTREPRINDERE.dbo.ANGAJATI
INNER JOIN INTREPRINDERE.dbo.INGINERI
ON INGINERI.IdAngajat = ANGAJATI.IdAngajat
WHERE INGINERI.Specialitatea ='Electronica'

--3.12
SELECT ANGAJATI.Nume, ANGAJATI.Prenume
FROM INTREPRINDERE.dbo.ANGAJATI
INNER JOIN INTREPRINDERE.dbo.SECTII
ON ANGAJATI.IdSectie = SECTII.IdSectie
WHERE SECTII.Nume = 'Productie' AND ANGAJATI.Prenume = 'Ion'

--3.13
SELECT ANGAJATI.Nume, ANGAJATI.Prenume
FROM INTREPRINDERE.dbo.ANGAJATI
INNER JOIN INTREPRINDERE.dbo.SECTII
ON ANGAJATI.IdSectie = SECTII.IdSectie
WHERE SECTII.Nume = 'Productie'


--3.14
SELECT ANGAJATI.Nume,ANGAJATI.Prenume
FROM INTREPRINDERE.dbo.ACHIZITII
INNER JOIN  INTREPRINDERE.dbo.ANGAJATI
ON ACHIZITII.IdAchizitor  = ANGAJATI.IdAngajat
INNER JOIN INTREPRINDERE.dbo.FURNIZOR
ON FURNIZOR.IdFurnizor = ACHIZITII.IdFurnizor
WHERE FURNIZOR.Nume = 'Popescu' AND FURNIZOR.Prenume = 'Razvan'

--3.15
SELECT ANGAJATI.Nume,ANGAJATI.Prenume
FROM INTREPRINDERE.dbo.VANZARI
INNER JOIN INTREPRINDERE.dbo.CLIENTI
ON CLIENTI.IdClient = VANZARI.IdClient
INNER JOIN INTREPRINDERE.dbo.ANGAJATI
ON ANGAJATI.IdAngajat = VANZARI.IdVanzator
WHERE CLIENTI.Nume='Marinescu' AND CLIENTI.Prenume='Ion';

--3.16
SELECT PRODUSE.Denumire
FROM INTREPRINDERE.dbo.COMPONENTE
INNER JOIN INTREPRINDERE.dbo.COMPOZITIE
ON COMPONENTE.IdComponenta = COMPOZITIE.IdComponenta
INNER JOIN INTREPRINDERE.dbo.PRODUSE
ON PRODUSE.IdProdus = COMPOZITIE.IdProdus
INNER JOIN INTREPRINDERE.dbo.ACHIZITII
ON ACHIZITII.IdComponenta = COMPONENTE.IdComponenta
INNER JOIN INTREPRINDERE.dbo.FURNIZOR
ON ACHIZITII.IdFurnizor = FURNIZOR.IdFurnizor
WHERE FURNIZOR.Nume = 'Danescu' AND FURNIZOR.Prenume = 'Ovidiu'

--3.17
SELECT PRODUSE.Denumire
FROM INTREPRINDERE.dbo.COMPONENTE
INNER JOIN INTREPRINDERE.dbo.COMPOZITIE
ON COMPONENTE.IdComponenta = COMPOZITIE.IdComponenta
INNER JOIN INTREPRINDERE.dbo.PRODUSE
ON PRODUSE.IdProdus = COMPOZITIE.IdProdus
INNER JOIN INTREPRINDERE.dbo.ACHIZITII
ON ACHIZITII.IdComponenta = COMPONENTE.IdComponenta
INNER JOIN INTREPRINDERE.dbo.FURNIZOR
ON ACHIZITII.IdFurnizor = FURNIZOR.IdFurnizor
WHERE FURNIZOR.Nume = 'Danescu' AND FURNIZOR.Prenume = 'Ovidiu'